"""empty message

Revision ID: 057c2b1691d4
Revises: a45f4dfde53b
Create Date: 2023-05-26 15:25:33.119540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057c2b1691d4'
down_revision = 'a45f4dfde53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ldap_account', sa.String(length=255), nullable=True))

    with op.batch_alter_table('message_feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ldap_account', sa.String(length=255), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ldap_account', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('ldap_account')

    with op.batch_alter_table('message_feedbacks', schema=None) as batch_op:
        batch_op.drop_column('ldap_account')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('ldap_account')

    # ### end Alembic commands ###
