"""empty message

Revision ID: 7c7c4634a1b2
Revises: 057c2b1691d4
Create Date: 2023-05-26 16:41:12.259605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7c4634a1b2'
down_revision = '057c2b1691d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ldap_account', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('ldap_account')

    # ### end Alembic commands ###
