"""empty message

Revision ID: 97a2506d3ced
Revises: 9f4e3427ea84
Create Date: 2023-05-25 17:37:49.588370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a2506d3ced'
down_revision = '9f4e3427ea84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ldap_account', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('id_token')
        batch_op.drop_column('ldap_account')

    # ### end Alembic commands ###
